nodeLinker: node-modules
enableGlobalCache: true

enableImmutableInstalls: false
enableInlineBuilds: false
enableTelemetry: false
httpTimeout: 60000

logFilters:
  - code: YN0006  # Uses deprecated option
    level: discard
  - code: YN0007  # Multiple versions of same package
    level: discard
  - code: YN0008  # Unused dependencies
    level: discard
  - code: YN0013  # Resolution issues
    level: discard
  - code: YN0019  # Workspace dependency issues
    level: discard

npmRegistryServer: "https://registry.yarnpkg.com"
